// _________________________________________________________________________ //
// *----------------------------- Information -----------------------------* //
/*
  Contains all URLS generated by users.
  NOTE: This database is stateless and will reset on server shutdown.

  Sample URLS are present by default for testing.
*/

const urls = {
  'sample1': {
    longURL: 'http://www/lighthouselabs.ca',
    userID: 'userRandomID'
  },
  'sample2': {
    longURL: 'http://www.google.com',
    userID: 'user2RandomID'
  }
};

module.exports = { urls };